Slice/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.contrib import admin
admin.autodiscover()

from Slice import views

'''
Maps URL to webpages
	- Uses regex
	partterns(A, url(B, C))

	A = the base url. 
		i.e if you have multiple url and they all start with the same prefix
		e.g instead of 
				patterns("", 
					url(r"^cakeyface/admin", include(whatever)),
					url(r"^cakeyface/powder", include(whatever))
						// ... etc
					)
			we can go
				patterns("^cakeyface",
					url(r"^admin", include(whatever)),
					url(r"^powder", include(whatever))
					)
	
	B = the regex you need to map the url.
		e.g r"^admin/" maps <our domain root>/admin/ to admin.site.urls

	C = include(). The site we maps the defined URL to.
		We map to the app's urls.py file
		The app's urls.py file will the direct us to the actual page we want.
		More on that in Deal/urls.py
'''
urlpatterns = patterns("",
    url(r"^$", views.index, name="home"),
    url(r"^admin/", include(admin.site.urls)),
    url(r"^account/", include("account.urls")),
    url(r"^profile/", include("UserProfile.urls")),
    url(r"^deals/", include('deal.urls')),
    url(r"^about/$", TemplateView.as_view(template_name="about_us.html"), name="about"),
    url(r"^support/$", TemplateView.as_view(template_name="support.html"), name="support"),
    url(r"^users/", include('Users.urls'))
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from __future__ import unicode_literals

from django.conf.urls import patterns, url

from account.views import SignupView, LoginView, LogoutView, DeleteView
from account.views import ConfirmEmailView
from account.views import ChangePasswordView, PasswordResetView, PasswordResetTokenView
from account.views import SettingsView


urlpatterns = patterns("",
    url(r"^signup/$", SignupView.as_view(), name="account_signup"),
    url(r"^login/$", LoginView.as_view(), name="account_login"),
    url(r"^logout/$", LogoutView.as_view(), name="account_logout"),
    url(r"^confirm_email/(?P<key>\w+)/$", ConfirmEmailView.as_view(), name="account_confirm_email"),
    url(r"^password/$", ChangePasswordView.as_view(), name="account_password"),
    url(r"^password/reset/$", PasswordResetView.as_view(), name="account_password_reset"),
    url(r"^password/reset/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$", PasswordResetTokenView.as_view(), name="account_password_reset_token"),
    url(r"^settings/$", SettingsView.as_view(), name="account_settings"),
    url(r"^delete/$", DeleteView.as_view(), name="account_delete"),
)

deal/urls.py
from django.conf.urls import patterns, url
from deal import views
import Pledge.views
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

from deal.models import Deal

#performance!!
#also, will have problem if no deals in database
deals = Deal.objects.all()
if deals:
    max_id = deals.order_by("-id")[0].id
else:
    max_id = 0
length = len(str(max_id))

deal_detail_regex = r'^([0-9]{1,'+ str(length)  +'})/'


'''
	Just like Slice/urls.py, we have a urlpatterns object.
	Unlike Slice/urls.py, we are not mapping regex to apps
	we are mapping regex to html page.

'''
urlpatterns = patterns('',
		# <root domain>/deal/ will map to our index
        url(r'^$', views.index, name="deals_index"),
        url(r'^create', views.create_deal_check_login, name="deal_create"),
        url(r'^help', TemplateView.as_view(template_name="deal_help.html"), name="deal_help"),
        url(deal_detail_regex+"$", views.detail, name="deal_detail"),
        url(deal_detail_regex+"edit/$", views.edit_deal, name = "deal_edit"),
        url(deal_detail_regex+"pledges/$", views.deal_view_pledges, name = "deal_view_pledges"),
        ) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Pledge/models.py
from django.db import models

from deal.models import Deal
from UserProfile.models import Profile

# Create your models here.
class Commitment(models.Model):
    user = models.ForeignKey(Profile)
    deal = models.ForeignKey(Deal)
    units = models.PositiveIntegerField()
    time_commited = models.DateTimeField(auto_now_add=True)
    requests = models.TextField(max_length=200, blank=True)

    #auto_now_add disallow editing in admin mode
    last_modified_date = models.DateTimeField(auto_now=False)

    def __unicode__(self):
        return str(self.user) + " " +  str(self.deal)

deal/views.py
from django.shortcuts import render, redirect
from django.http      import HttpResponse, HttpResponseRedirect
from django.template  import RequestContext
from django.shortcuts import render_to_response
from django.core.urlresolvers import reverse
from django.views.generic import TemplateView
from django.shortcuts import get_object_or_404
from django.core.exceptions import ObjectDoesNotExist
from django.utils import timezone

#https://docs.djangoproject.com/en/1.7/topics/db/queries/#complex-lookups-with-q-objects
from django.db.models import Q, Avg, Sum

#Pinax
from account import urls

#Models
from deal.forms  import CreateDealForm, SearchDealForm, RateDealForm, UploadImageForm, EditDealForm
from deal.models import Deal, Rating
from django.contrib.auth.models import User
from UserProfile.models import Profile, History
from Pledge.forms import CommitmentForm
from Pledge.models import Commitment

from Slice.helper import get_sorted_model, get_paginator


def getStringFromInput(form, s):
    """ Retrieves the string value from the input field in the given form  """
    data = form.cleaned_data[s]
    return None if data is None else data.strip()

def index(request):
    context = RequestContext(request)
    now = timezone.localtime(timezone.now())
    deals = Deal.objects.filter(end_date__gte=now)

    form = SearchDealForm(data=request.GET)
    queries_without_page = request.GET.copy()
    if queries_without_page.get('page', None):
        del queries_without_page['page']


    if  'search-deals' in request.GET and form.is_valid():
        search_key = getStringFromInput(form, 'search')
        min_price  = form.cleaned_data['min_price']
        max_price  = form.cleaned_data['max_price']
        start      = form.cleaned_data['start_date']
        end        = form.cleaned_data['end_date']
        category   = form.cleaned_data['category']

        #https://docs.djangoproject.com/en/dev/ref/models/querysets/
        q = Q()
        if search_key:
            q |= Q(title__iexact=search_key)
            q |= Q(short_desc__contains=search_key)
            q |= Q(description__contains=search_key)

        if min_price:  q &= Q(cost_per_unit__gte=float(min_price))
        if max_price:  q &= Q(cost_per_unit__lte=float(max_price))
        if start:      q &= Q(start_date__gte=start)
        if end:        q &= Q(end_date__lte=end)
        if category:   q &= Q(category_id__exact=category.id)

        deals = Deal.objects.filter(q)

    deals = get_sorted_model(request, deals)
    deals, last_page = get_paginator(deals, request)


    context_dict = {'deals': deals,
                    'search_form': form,
                    'now': now,
                    'last_page':last_page,
                    'query': queries_without_page}


    return render_to_response('deal_index.html', context_dict, context)

def is_valid_dates(start, end):
    now = timezone.localtime(timezone.now())
    return start >= now and end > now and start < end


def create_deal_check_login(request):
    if not request.user.is_authenticated():
    #redirect to login page
       return HttpResponseRedirect('/account/login?next=' + request.path )

    success = False
    form = CreateDealForm()
    search_form = SearchDealForm()

    if 'submit-deal' in request.POST:
       form = CreateDealForm(request.POST, request.FILES)

       if form.is_valid():
           deal = form.save(commit=False)
           deal.owner_id = request.user.id
           deal.available_units = deal.num_units
           img = request.FILES.get('thumbnail', None)
           deal.thumbnail = img if img else "default.svg"
           deal.save()
           success = True
       else:
            print form.errors
    elif 'submit-cancel' in request.POST:
        return HttpResponseRedirect(reverse('deals_index'))
    return render(request, 'create_deal.html', { 'form': form,
                                                 'request': request,
                                                 'search_form': search_form,
                                                 'valid_form': success},)

def detail(request, pk):
    try:
        found_deal = Deal.objects.get(id=pk)
    except:
        found_deal = None
    if not found_deal: return render(request, 'deal_detail.html', {'deal':found_deal, 
                                                                   'error_message': "No deal is found. Did you enter the correct URL?"})

    signed_in = request.user.is_authenticated()
    current_viewer = None if not signed_in else Profile.objects.get(account_id=request.user.id)
    deal_owner = User.objects.get(id=found_deal.owner_id)
    pledge_form = CommitmentForm()
    rate_form = RateDealForm()
    error_message = None


    # don't want double history on bookmarking/pledging
    # will have double history on refresh though
    if signed_in and request.method != 'POST':
        History(user=current_viewer, deal=found_deal).save()

    try:
        has_pledged = Commitment.objects.filter(deal_id=pk, user_id=request.user.id)
    except ObjectDoesNotExist:
        has_pledged = False

    claimed_units = Commitment.objects.filter(deal_id=found_deal.id).aggregate(Sum('units'))
    #in case no claimed units yet
    if claimed_units['units__sum'] == None:
        units_left = found_deal.num_units
    else:
        units_left = found_deal.num_units - claimed_units['units__sum']

    if 'submit-pledge' in request.POST:
        pledge_form = CommitmentForm(request.POST)
        if pledge_form.is_valid():
            request_units = pledge_form.cleaned_data['units']
            now = timezone.localtime(timezone.now())
            if request_units > units_left:
                error_message = "There are not enough units to go around. Please reduce your units"
            elif now > found_deal.end_date:
                error_message = "You cannot pledge anymore. The deal has expired!"
            elif found_deal.start_date > now:
                error_message = "You cannot pledge yet. Please wait till the deal starts!"
            elif found_deal.min_pledge_amount > request_units:
                error_message = "You need to pledge at least " + str(found_deal.min_pledge_amount) + " unit!"
            else:
                pledge = pledge_form.save(commit=False)
                pledge.last_modified_date= timezone.localtime(timezone.now())
                pledge.user = current_viewer
                pledge.deal = found_deal
                pledge.save()

                has_pledged = True
    elif 'bookmark' in request.POST:
        current_viewer.bookmarks.add(found_deal)
    elif 'remove-bookmark' in request.POST:
        current_viewer.bookmarks.remove(found_deal)
    elif 'rate-deal' in request.POST:
        rate_form = RateDealForm(request.POST)
        if rate_form.is_valid():
            try:
                rate = Rating.objects.get(deal=found_deal, user=current_viewer)
            except ObjectDoesNotExist:
               rate = Rating.objects.create(deal=found_deal, user=current_viewer)
            rate.rating = rate_form.cleaned_data['rating']
            rate.save()

    bookmark = []
    if signed_in and current_viewer:
        try:
            bookmark = current_viewer.bookmarks.get(id=found_deal.id)
        except ObjectDoesNotExist:
            bookmark = None
    else:
        pledge_form = None
        has_pledged = False

    current_rating = Rating.objects.filter(deal=found_deal)

    if current_rating:
        avg_rating = current_rating.aggregate(Avg('rating'))
        avg_rating = avg_rating['rating__avg']
    else:
        avg_rating = "This deal has no ratings yet. Be the first one to rate it!"

    is_expired = (found_deal.end_date < timezone.localtime(timezone.now()))

    if is_expired: error_message = "Deal has expired"


    context_dict = {'deal': found_deal,
                    'owner': deal_owner,
                    'pledge_form': pledge_form,
                    'has_pledged': has_pledged,
                    'bookmark': bookmark,
                    'signed_in': signed_in,
                    'rate_form': rate_form,
                    'avg_rating': avg_rating,
                    'is_expired': is_expired,
                    'units_left': units_left,
                    'user': request.user,
                    'error_message': error_message}
    return render(request, 'deal_detail.html', context_dict)


def edit_deal (request, pk):
    if not request.user.is_authenticated():
        #redirect to login page
        return HttpResponseRedirect('/account/login?next=' + request.path)
    
    try:
        deal_entry = Deal.objects.get(id=pk)
    except ObjectDoesNotExist:
        deal_entry = None
    if not deal_entry:
        error_message = "You do not have right to modify this deal"
        return render(request, 'edit_deal.html', {'error_message':error_message})


    if request.user.id != deal_entry.owner_id:
        error_message = "You do not have right to modify this deal"
        return render(request, 'edit_deal.html', {'error_message':error_message})

    units_remained = deal_entry.num_units
    claimed_units = Commitment.objects.filter(deal_id=deal_entry.id).aggregate(Sum('units'))
    if claimed_units.get('units__sum', None):
        units_remained -= claimed_units['units__sum']

    if request.method == 'POST':
        form = EditDealForm(request.POST, request.FILES, instance=deal_entry)

        if form.is_valid():

            form.save()
            return redirect('profile_mydeals')
    else:
        form = EditDealForm(initial={'title':deal_entry.title,
                                 'short_desc':deal_entry.short_desc,
                                 'description':deal_entry.description,
                                 'category':deal_entry.category,
                                 'cost_per_unit':deal_entry.cost_per_unit,
                                 'num_units':deal_entry.num_units,

deal/templates/create_deal.html
{% extends "deal_base.html" %}
{% load i18n %}

{%block content %}
  {% if valid_form %}
    <div class="alert alert-success" role="alert">
      You have successfuly made a deal!
    </div>
    {% else %}
    {% if form.errors %}
      <div class="alert alert-danger" role="alert"> 
        You have errors in your submission. Please make necessary changes!
      </div>
      {% endif %}
      {% load widget_tweaks%}
     
    <form role="form" method="post" action="{% url 'deal_create' %}" enctype="multipart/form-data" data-ajax="false">
      {% csrf_token %}
      {% for field in form %}
        {% if field.errors %}
          <div class="form-group has-error has-feedback">
        {% else %}
        <div class="form-group">
          {% endif %}
          <label >{{ field.label }}</label>
          {% render_field field placeholder=field.help_text %}
            {% for error in field.errors%}
          <span class="help-block">
            <strong>{{ error|escape }}</strong>
          </span>
        {% endfor %}

        </div>
        {% endfor %}
        <input type="submit" value="Create!" class="btn btn-success" name="submit-deal"  />
        <input type="submit" value="Cancel" class="btn btn-default" name="submit-cancel" style="float: right;" />
              <a href="{% url 'deal_help' %}"> Help </a>
    </form>

  {% endif %}

{% endblock %}

deal/templates/deal_base.html
{% extends "site_base.html" %}

{% load i18n %}

{% block body %}
<div class="container">
  {% load widget_tweaks %}

  <div class="row">
    <!-- search form -->
    <form role="form" action="{% url 'deals_index' %}" method="get" id="deal-nav" class="form-horizontal col-md-2">

      <div class="form-group">
        <label>{{ search_form.search.label }}</label>
        <div class="input-group">
          <div class="input-group-addon"><span class="glyphicon glyphicon-search"></span></div>
          {{ search_form.search }}
        </div>
      </div>


      <div class="form-group">
        <label>{{ search_form.min_price.label }}</label>
        <div class="input-group">
          <div class="input-group-addon">$</div>
          {{ search_form.min_price }}
        </div>
      </div>

      <div class="form-group">
        <label>{{ search_form.max_price.label }}</label>
        <div class="input-group">
          <div class="input-group-addon">$</div>
          {{ search_form.max_price }}
        </div>
      </div>

      <div class="form-group">
        <label>{{ search_form.start_date.label }}</label>
        {{ search_form.start_date | attr:"id:search_start_date" |attr:"placeholder:dd/mm/yyyy" }}
      </div>

      <div class="form-group">
        <label>{{ search_form.end_date.label }}</label>
        {{ search_form.end_date | attr:"id:search_end_date" |attr:"placeholder:dd/mm/yyyy"  }}
      </div>

      <div class="form-group">
        <label>{{ search_form.category.label }}</label>
        {{ search_form.category }}
      </div>

      <div class="form-group">
        <input type="submit" value="Search" class="btn btn-default" name="search-deals" />
      </div>
    </form>
    <!-- End search form -->

    <div class="col-md-10" id="deal-content">
      {% block content %} <!-- content block -->


      {% endblock %}
    </div> <!-- end deal-content -->
  </div> <!-- end row -->
</div> <!-- end container -->
{% endblock %}




<!--
This is the template for our Deal app.
If you change this, all webpages in Deal that extends this file will be changed.

Our content will be automatically rendered in between the content block (see above code)

-->

deal/templates/deal_detail.html
{% extends "site_base.html" %}
{% load i18n %}
{% block body %}

<div class="container">

  {% if deal %}
  <div class="row">
    <div class="col-md-8" id="deal-content">
      {% block content %} <!-- content block -->

      <h1> {{deal.title}}  </h1> provided by <a href="{% url 'users_detail' owner.id %}">{{owner.username}}</a>
      {% if signed_in%}
      <form role="form" method="post" action="{% url 'deal_detail' deal.id %}">
        {% csrf_token %}
        {% if not bookmark %}
        <input type="submit" value="Bookmark this deal!" class="btn btn-default" name="bookmark" />
        {% else %}
        <input type="submit" value="Remove from bookmark" class="btn btn-danger" name="remove-bookmark" />
        {% endif %}
      </form>
      {% endif %}
      <br/>
      <strong>Rating: </strong> {{avg_rating}} <br/>
      {% if not is_expired and user.is_authenticated and deal.owner.account_id != user.id %}
      <form role="form" method="post" action="{% url 'deal_detail' deal.id %}">
        {% csrf_token %}
        <div class="form-group">
          {{rate_form}}
        </div>
          <input type="submit" value="Rate Deal" class="btn btn-default" name="rate-deal" />
        </form>

        {% endif %}

      <h4> Description </h4>
      <p> {{deal.description}}  </p>
      <h4> Features and Benefits </h4>
      <p> {{deal.features_benefits}}  </p>
      <p><strong>Start Date:</strong> {{deal.start_date}} </p>
      <p><strong>Due Date:</strong> {{deal.end_date}} </p>
      {% if deal.cost_per_unit%}
      <p><strong>Price:</strong> ${{deal.cost_per_unit}} </p>
      {% endif %}
      {% if deal.non_monetary_condition %}
      <p><strong>Non monetary condition: </strong> {{deal.non_monetary_condition}}</p>
      {% endif %}
      {% if deal.savings_per_unit %}
      <p><strong>Savings involved per unit:</strong> ${{deal.savings_per_unit}} </p>
      {% endif %}
      <p><strong>Units left:</strong> {{units_left}}
      <p><strong>Delivery method:</strong> {{deal.delivery_method}}</p>
      <p><strong>Minimum Total Pledges Required:</strong> {{deal.min_pledge_amount}}</p>



      {% endblock %}
    </div> <!-- end deal-content -->

    <div class="col-md-4">
      <div style="width: 100%; height: 15em; background: #000; color: #fff">
        Images
      </div>
      <div style="width: 100%; height: 15em; background: #000; color: #fff; margin-top: 1em;">
        Images
      </div>
    </div>
  </div> <!-- end row -->

  {% if error_message%}
   <div class="alert alert-danger" role="alert">
       {{error_message}}
    </div>
    {% endif %}

    {% if units_left <= 0 %}
    <div class="alert alert-info" role="alert"> 
        This deal has no units left! :( <br/>
        Thank you for your interest!
    </div>
    {% endif %}

    {% if has_pledged %}
      <div class="alert alert-success" role="alert" style="margin-top: 1em;">
        You have already pledged! 
        <a href="{% url 'pledge_edit' deal.id %}"><button class="btn btn-default">Take me to my pledge</button></a>
      </div>
    {% endif %}

    {% if not signed_in %}
      Please signin to make a commitment!
    {% endif %}

    {% if signed_in and units_left > 0 and not has_pledged and not is_expired %}
  <div class="row">
    <h1> Make a Pledge </h1>
          <form role="form" method="post" action="{% url 'deal_detail' deal.id %}">
            {% csrf_token %}

            {% for field in pledge_form %} {# start pledge_form for #}
              {% if field.errors %}
                <div class="form-group has-error has-feedback"> <!-- start form-group div -->
              {% else %}
                <div class="form-group">
              {% endif %}

              <label> {{field.label}} </label>
              {{field}}

              {% for error in field.errors%}
                <span class="help-block">
                  <strong>{{ error|escape }}</strong>
                </span>
              {% endfor %} {# end for field.errors #}

                </div> <!-- end form-group div -->
            {% endfor %} {# end pledge_form for#}

            <input type="submit" value="Cut me a Slice!" class="btn btn-default" name="submit-pledge" />

          </form>



  </div> <!-- end row -->

    {% endif %}

  {% endif %} {# end if deal  #}

</div> <!-- end container -->
{% endblock %}

deal/templates/deal_help.html
{% extends "banner_base.html"%}

{% block banner %}
    <h1>Create Deal Help</h1>
    <p>
    Help
    </p>

{% endblock %}

deal/templates/deal_index.html
{% extends "deal_base.html" %}

{% block content %}


<a href="{% url 'deal_create' %}"><button class="btn btn-success">Create Deal </button></a>

{% include 'sort_button.html'%}
  {% for deal in deals %}
<div class="media">
  <a class="pull-left" href="#">
    <img class="media-object" src="/site_media/media/{{deal.thumbnail}}" >
    </a>
    <div class="media-body">
      <h4 class="media-heading" style="display:inline;">
        <a href="{% url 'deal_detail' deal.id %}">{{ deal.title }}</a>
      </h4>
        <span style="float:right;">Ends on {{ deal.end_date }}</span>
      {% if deal.start_date <= now and deal.end_date > now %}
          <span class="badge alert-success">Active</span>
      {% elif deal.start_date <= now and deal.end_date <= now %}
          <span class="badge alert-danger">Ended</span>
      {% elif deal.start_date > now %}
          <span class="badge alert-info">Coming soon</span>
      {% endif %}

    </br>
      {{ deal.short_desc }} <br/>
    </div>

</div>

{% endfor %}
{% if not deals%}
  <div class="alert alert-danger" role="alert">
    No deals found!
  </div>
{% endif %}

{% include "pigination.html" %}
{% endblock %}

deal/templates/deal_nav.html
<form role="form" action="/your-name/" method="get" id="deal-nav" class="form-horizontal col-md-2">
	<div class="form-group">
    	<label for="price">Price </label>
    	<input id="price" type="text" name="price" class="form-control">
    </div>

    <div class="form-group">
    	<label for="Name">Name </label>
    	<input id="Name" type="text" name="Name" class="form-control">
    </div>

    <div class="form-group">
    	<label for="Tag">Tag </label>
    	<input id="Tag" type="text" name="Tag" class="form-control">
    </div>

	<h6>Deal States:</h6>


    <div class="checkbox">
  		<label>
    		<input type="checkbox" value="">
			Open
  		</label>
	</div>

	 <div class="checkbox">
  		<label>
    		<input type="checkbox" value="">
			Closed
  		</label>
	</div>

	 <div class="checkbox">
  		<label>
    		<input type="checkbox" value="">
			Started
  		</label>
	</div>

    <input type="submit" value="OK" class="btn btn-default">
</form>

deal/templates/deal_view_pledges.html
{% extends "profile_base.html" %}

{% block content %}
<h1>Deal: {{deal.title}}</h1> 
<h2>Pledges: </h2>
{% if error_message%}
<div class="alert alert-danger" role="alert">
  {{error_message}}
</div>
{% else %}

   {% for p in user_profiles %}
<div class="well">
  <label>Username: </label> {{p.account.user.username}} <br/>
  <label>Email: </label> {{p.account.user.email}} <br/>
  {% for i in p.commitment_set.all%}
    {% if i.deal.id == pk %}
        <label>Units: </label>{{i.units}}<br/>
        <label>Requests: </label>{{i.requests}} <br/>
    {% endif %}
  {% endfor %}
</div>
   {% endfor %}



  {% if not user_profiles %}
   <div class="alert alert-warning" role="alert">
      Nobody has commited yet! Please check again later!
   </div>
  {% endif %}
{% endif %}
{% endblock %}

deal/templates/edit_deal.html
{% extends "profile_base.html" %}

{% block content %}
{% if error_message%}
<div class="alert alert-danger" role="alert">
  {{error_message}}
</div>
{% endif %}
{% if not error_message %}
    <div class="panel panel-default" id="account-details">
        <div class="panel-heading">Edit Deal</div>

        <div class="panel-body" id="account-body">
    	    <form role="form" method="post" action="{% url 'deal_edit' deal.id %}" enctype="multipart/form-data" data-ajax="false">{% csrf_token %}

            {% for field in edit_form %}
            <div class="form-group">
                <label>{{field.label}}</label>
                {{field}}
            </div>
            {% endfor %}

            
            {% for field in image_edit %}
            <div class="form-group">
                <label>{{field.label}}</label>
                {{field}}
            </div>
            {% endfor %}

    		<a href="{% url 'profile_mydeals'%}">
                <button class="btn btn-default">Cancel</button>
            </a>
            <input type="submit" value="Save" class="btn btn-default" name="save-deal-details" id="account-save-btn" />
        </form>
    </div>
  </div>
  {% endif %}
{% endblock %}

deal/templates/sort_button.html
<div class="btn-group" style="float: right;">
  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" style="width: 100px;">
        Sort by <span class="caret"></span>
  </button>
<ul class="dropdown-menu" role="menu">
  <li><a href="?sort=price_lth">Price (lowest to highest)</a></li>
  <li><a href="?sort=price_htl">Price (highest to lowest)</a></li>

 <li class="divider"></li>
 <li><a href="?sort=alpha_lth">Title (a-z)</a></li>
  <li><a href="?sort=alpha_htl">Title (z-a)</a></li>
  <li class="divider"></li>

  <li><a href="?sort=end_date_lth">End date (closest to furthest)</a></li>
  <li><a href="?sort=end_date_htl">End date (furthest to closest)</a></li>
  <li class="divider"></li>
  <li><a href="?sort=start_date_lth">Start date (closest to furthest)</a></li>
  <li><a href="?sort=start_date_htl">Start date (furthest to closest)</a></li>

  </ul>
</div>